### ISSUE TITLE
Feature request: Option to monitor multiple uwsgi apps/socks

### ISSUE THREAD

**Issue by naveen-tenmiles** [timonwong/uwsgi_exporter#31] opened 2019-06-10 12:13 UTC
We currently run more than 10 wsgi process per server node, 
each uwsgi process need to be monitored, running individual exporter per uwsgi apps becomes tedious with prometheus scrap config in dynamic wsgi apps, where apps are auto scaled up and down.

**Comment by wimoMisterX** [comment] 2019-08-13 07:33
+1

**Comment by francis826** [comment] 2019-10-16 17:04
Duplicate of https://github.com/timonwong/uwsgi_exporter/issues/30 but I still think this would be really nice!

**Closed** 2023-03-23 03:11 UTC
